services:
  # springboot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.development
  #   container_name: springboot
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8080:8080"
      
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - softdev_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8888:80"
    depends_on:
      - db

volumes:
  softdev_data: